### PR TITLE
 #17 issue solved

### PR DESCRIPTION
**Pull request by huzaifansari54**
**### update query parameter according to official hugging face api docs**

### CODE REVIEW

**Comment by huzaifansari54** [comment]
it has some conflicts let me know where I have to make changes

**Comment by shamblett** [comment]
Its up to you to resolve your conflicts, did you update your fork to latest main branch before creating this PR?

**Comment by huzaifansari54** [comment]
no!

**Comment by huzaifansari54** [comment]
closed

**Pull request closed without merging**
